[package]
name = "evm-bench"
version = "0.1.0"
authors = ["Ziyad Edher <ziyad.edher@gmail.com>"]
edition = "2021"
description = "🚀🪑 evm-bench is a suite of Ethereum Virtual Machine stress tests and benchmarks."
homepage = "https://github.com/ziyadedher/evm-bench"
repository = "https://github.com/ziyadedher/evm-bench"
keywords = ["benchmark", "ethereum", "evm"]

[dependencies]
bytes = "1.5"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
glob = "0.3"
hex = "0.4"
itertools = "0.12"
jsonschema = "0.17"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
tabled = "0.15"
users = "0.11"
