[package]
name = "evm-bench"
version = "0.1.0"
authors = ["Ziyad Edher <ziyad.edher@gmail.com>"]
edition = "2021"
description = "🚀🪑 evm-bench is a suite of Ethereum Virtual Machine stress tests and benchmarks."
homepage = "https://github.com/ziyadedher/evm-bench"
repository = "https://github.com/ziyadedher/evm-bench"
keywords = ["benchmark", "ethereum", "evm"]

[workspace]
members = ["./", "runners/revm/"]
default-members = ["./"]
resolver = "2"

[dependencies]
alloy-primitives = { version = "0.7", features = ["serde"] }
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
comfy-table = { version = "7", default-features = false }
glob = "0.3"
itertools = "0.12"
jsonschema = "0.17"
serde = "1.0"
serde_json = "1.0"
users = "0.11"
which = "6"

color-eyre = "0.6"
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[profile.runner]
inherits = "release"
opt-level = 3
lto = "fat"
panic = "abort"
debug = "line-tables-only"
codegen-units = 1
